name: once_upon_a_line
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_bloc: ^8.1.6
  formz: ^0.8.0
  equatable: ^2.0.5
  intl: ^0.20.2
  go_router: ^15.1.3
  get_it: ^8.1.2
  shared_preferences: ^2.5.4
  logger: ^2.6.2
  flutter_dotenv: ^5.1.0
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  
  # UI & Utils
  cached_network_image: ^3.4.1
  uuid: ^4.5.2
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/app_icon.png
  image_path_ios: assets/images/app_icon.png
  remove_alpha_ios: true
  min_sdk_android: 21
